# Generated by Django 5.1.7 on 2025-05-06 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_product_weight_shipping_estimated_delivery_date_and_more'),
        ('userapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bill',
            name='currency',
            field=models.CharField(blank=True, default='USD', help_text='The currency used for the payment.', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='common.payment'),
        ),
        migrations.AddField(
            model_name='bill',
            name='refund_status',
            field=models.CharField(blank=True, choices=[('not_refunded', 'Not Refunded'), ('refunded', 'Refunded'), ('partial_refund', 'Partial Refund')], default='not_refunded', help_text='The status of any refund associated with this bill.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderline',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='returnrefund',
            name='approved_refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The approved refund amount (if different from requested).', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='returnrefund',
            name='escalation_reason',
            field=models.TextField(blank=True, help_text='Reason for escalation, if any.', null=True),
        ),
        migrations.AddField(
            model_name='returnrefund',
            name='refund_method',
            field=models.CharField(blank=True, choices=[('credit_card', 'Credit Card'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('cash_on_delivery', 'Cash on Delivery')], help_text='The method used to process the refund.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='returnrefund',
            name='resolution_notes',
            field=models.TextField(blank=True, help_text='Additional notes regarding the resolution of the return/refund.', null=True),
        ),
        migrations.AddField(
            model_name='returnrefund',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns_resolved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='returnrefund',
            name='return_date',
            field=models.DateTimeField(blank=True, help_text='Date when the product was returned.', null=True),
        ),
    ]
