# Generated by Django 5.1.7 on 2025-03-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='userphoto',
            field=models.ImageField(blank=True, default='user_photos/default.jpg', null=True, upload_to='user_photos/'),
        ),
    ]
