# Generated by Django 5.1.7 on 2025-05-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_product_weight_shipping_estimated_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
