# Generated by Django 5.1.7 on 2025-06-17 12:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_payment_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='added_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='common.subcategory'),
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('interaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('view', 'Viewed'), ('search', 'Searched'), ('favorite', 'Favorited'), ('cart', 'Added to Cart'), ('purchase', 'Purchased')], max_length=20)),
                ('weight', models.FloatField(default=1.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('context', models.JSONField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='common.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='common_inte_user_id_5d71ae_idx'), models.Index(fields=['product', 'action'], name='common_inte_product_79f92f_idx'), models.Index(fields=['session_key'], name='common_inte_session_3fd866_idx')],
            },
        ),
    ]
