# Generated by Django 5.1.7 on 2025-03-25 06:31

import django.db.models.deletion
import django.utils.timezone
import sellerapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Title for the banner, e.g., 'Limited Time Offer'", max_length=255)),
                ('description', models.TextField(help_text='Description for the banner')),
                ('offer_details', models.CharField(blank=True, help_text="Offer details, e.g., 'Up to 50% off'", max_length=255)),
                ('image', models.ImageField(blank=True, help_text='Banner background image', null=True, upload_to='banners/')),
                ('start_date', models.DateTimeField(help_text='Start date for displaying the banner')),
                ('end_date', models.DateTimeField(help_text='End date for displaying the banner')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle to enable/disable the banner')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='DiscountCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=50)),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=sellerapp.models.default_discount_card_end_date)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FreeShippingOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_order_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=sellerapp.models.default_free_shipping_end_date)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('success', 'Success'), ('error', 'Error'), ('admin', 'Admin Notification'), ('seller', 'Seller Notification')], default='info', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('redirect_url', models.URLField(blank=True, null=True)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_filename', models.ImageField(upload_to='product_images/')),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='common.productitem')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_title', models.CharField(help_text="Title for the offer, e.g., 'Special Discount'", max_length=255)),
                ('offer_description', models.TextField(blank=True, help_text='Description of the offer')),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Discount percentage, e.g., 20.00 for 20%', max_digits=5)),
                ('start_date', models.DateTimeField(help_text='Start date for the offer')),
                ('end_date', models.DateTimeField(help_text='End date for the offer')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle to enable/disable the offer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='common.product')),
            ],
            options={
                'verbose_name': 'Product Offer',
                'verbose_name_plural': 'Product Offers',
                'ordering': ['-start_date'],
            },
        ),
    ]
