# Generated by Django 5.1.7 on 2025-04-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image_filename',
        ),
        migrations.AddField(
            model_name='productimage',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='sub_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='sub_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='sub_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
