# Generated by Django 5.1.7 on 2025-05-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0002_remove_productimage_image_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='The time at which the notification will expire.', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', help_text='The priority level of the notification.', max_length=10, null=True),
        ),
    ]
